# Generated by Django 5.1.4 on 2024-12-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.TextField()),
                ('public_key', models.TextField()),
                ('uuid_compromised_pc', models.UUIDField()),
            ],
        ),
    ]
