# Generated by Django 5.1.4 on 2024-12-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keys',
            name='private_key',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='keys',
            name='public_key',
            field=models.BinaryField(),
        ),
    ]
