# Generated by Django 5.1.4 on 2024-12-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_keys_private_key_alter_keys_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys',
            name='encrypted_symetric_key',
            field=models.BinaryField(blank=True),
        ),
    ]
