# Generated by Django 5.1.4 on 2024-12-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_keys_encrypted_symetric_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys',
            name='paid_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='keys',
            name='unique_token',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
